# Form implementation generated from reading ui file 'ad_trangchu.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtWidgets import (QApplication, QMainWindow, QWidget, QPushButton, QVBoxLayout, 
                             QLineEdit, QLabel, QTableWidget, QScrollArea, QMenuBar, QStatusBar, QMenu)
from PyQt6.QtGui import QFont, QCursor, QAction  # Thêm QAction vào đây
from PyQt6 import QtCore
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ad_trangchu(object):
    def setupUi(self, ad_trangchu):
        ad_trangchu.setObjectName("ad_trangchu")
        ad_trangchu.resize(1523, 1262)
        ad_trangchu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        ad_trangchu.setAutoFillBackground(False)
        ad_trangchu.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.centralwidget = QtWidgets.QWidget(parent=ad_trangchu)
        self.centralwidget.setObjectName("centralwidget")
        
        self.ad_trangchu_thanhcongcu = QtWidgets.QWidget(parent=self.centralwidget)
        self.ad_trangchu_thanhcongcu.setGeometry(QtCore.QRect(0, 0, 1911, 111))
        self.ad_trangchu_thanhcongcu.setAutoFillBackground(False)
        self.ad_trangchu_thanhcongcu.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.ad_trangchu_thanhcongcu.setObjectName("ad_trangchu_thanhcongcu")
        self.ad_trangchu_them = QtWidgets.QPushButton(parent=self.ad_trangchu_thanhcongcu)
        self.ad_trangchu_them.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ad_trangchu_them.setFont(font)
        self.ad_trangchu_them.setAutoFillBackground(False)
        self.ad_trangchu_them.setStyleSheet("background-color: rgb(144, 144, 144);")
        self.ad_trangchu_them.setObjectName("ad_trangchu_them")
        self.ad_trangchu_sua = QtWidgets.QPushButton(parent=self.ad_trangchu_thanhcongcu)
        self.ad_trangchu_sua.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ad_trangchu_sua.setFont(font)
        self.ad_trangchu_sua.setAutoFillBackground(False)
        self.ad_trangchu_sua.setStyleSheet("background-color: rgb(144, 144, 144);")
        self.ad_trangchu_sua.setObjectName("ad_trangchu_sua")
        self.ad_trangchu_xoa = QtWidgets.QPushButton(parent=self.ad_trangchu_thanhcongcu)
        self.ad_trangchu_xoa.setGeometry(QtCore.QRect(10, 70, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.ad_trangchu_xoa.setFont(font)
        self.ad_trangchu_xoa.setAutoFillBackground(False)
        self.ad_trangchu_xoa.setStyleSheet("background-color: rgb(144, 144, 144);")
        self.ad_trangchu_xoa.setObjectName("ad_trangchu_xoa")
        self.chublogphim = QtWidgets.QLabel(parent=self.ad_trangchu_thanhcongcu)
        self.chublogphim.setGeometry(QtCore.QRect(150, 20, 671, 91))
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.chublogphim.setFont(font)
        self.chublogphim.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chublogphim.setObjectName("chublogphim")
        self.ad_trangchu_thanhtimkiem = QtWidgets.QLineEdit(parent=self.ad_trangchu_thanhcongcu)
        self.ad_trangchu_thanhtimkiem.setGeometry(QtCore.QRect(880, 40, 511, 31))
        self.ad_trangchu_thanhtimkiem.setAutoFillBackground(False)
        self.ad_trangchu_thanhtimkiem.setStyleSheet("background-color: rgb(144, 144, 144);")
        self.ad_trangchu_thanhtimkiem.setText("")
        self.ad_trangchu_thanhtimkiem.setObjectName("ad_trangchu_thanhtimkiem")
        self.ad_trangchu_timkiem = QtWidgets.QPushButton(parent=self.ad_trangchu_thanhcongcu)
        self.ad_trangchu_timkiem.setGeometry(QtCore.QRect(1400, 40, 91, 31))
        self.ad_trangchu_timkiem.setAutoFillBackground(False)
        self.ad_trangchu_timkiem.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"color: rgb(230, 230, 230);")
        self.ad_trangchu_timkiem.setObjectName("ad_trangchu_timkiem")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(180, 260, 1271, 881))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1269, 879))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1250, -1, 20, 881))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(10, 1, 1231, 861))
        self.tableWidget.resizeRowsToContents()
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        

        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.centralwidget.mousePressEvent = self.clear_table_selection

        self.tableWidget.setRowCount(100)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.tableWidget.setStyleSheet("""
                QTableWidget {
                    background-color: rgb(255, 255, 255);  /* Màu nền bảng */
                    color: rgb(0, 0, 0);  /* Màu chữ */
                    gridline-color: rgb(200, 200, 200);  /* Màu đường kẻ */
                }
                QHeaderView::section {
                    background-color: rgb(128,128,128);  /* Màu nền tiêu đề cột */
                    color: rgb(255, 255, 255);  /* Màu chữ tiêu đề cột */
                    font-weight: bold;
                }
                QTableWidget::item:selected {
                    background-color: rgb(192,192,192);  /* Màu nền khi chọn */
                    color: white;  /* Màu chữ khi chọn */
                }                               
                QTableWidget::item {
                    selection-background-color: rgb(200, 200, 255);  /* Màu nền khi chọn */
                    selection-color: rgb(0, 0, 0);  /* Màu chữ khi chọn */
                }
            """)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chublogphim_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.chublogphim_2.setGeometry(QtCore.QRect(230, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.chublogphim_2.setFont(font)
        self.chublogphim_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.chublogphim_2.setObjectName("chublogphim_2")
        ad_trangchu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ad_trangchu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1523, 26))
        self.menubar.setObjectName("menubar")
        self.ad_menu_trangchu = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ad_menu_trangchu.setFont(font)
        self.ad_menu_trangchu.setAutoFillBackground(False)
        self.ad_menu_trangchu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(6, 6, 6);")
        self.ad_menu_trangchu.setObjectName("ad_menu_trangchu")
        self.ad_menu_quanly_nguoidung = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ad_menu_quanly_nguoidung.setFont(font)
        self.ad_menu_quanly_nguoidung.setAutoFillBackground(False)
        self.ad_menu_quanly_nguoidung.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ad_menu_quanly_nguoidung.setObjectName("ad_menu_quanly_nguoidung")
        self.ad_menu_quanly_phim = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ad_menu_quanly_phim.setFont(font)
        self.ad_menu_quanly_phim.setAutoFillBackground(False)
        self.ad_menu_quanly_phim.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ad_menu_quanly_phim.setObjectName("ad_menu_quanly_phim")

        
        ad_trangchu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ad_trangchu)
        self.statusbar.setObjectName("statusbar")
        ad_trangchu.setStatusBar(self.statusbar)
        self.menubar.addAction(self.ad_menu_trangchu.menuAction())
        self.menubar.addAction(self.ad_menu_quanly_nguoidung.menuAction())
        self.menubar.addAction(self.ad_menu_quanly_phim.menuAction())

        self.ad_menu_trangchu_action = QAction("Trang chủ", parent=ad_trangchu)
        self.ad_menu_trangchu.addAction(self.ad_menu_trangchu_action)

        self.ad_menu_quanly_nguoidung_action = QAction("Quản lý người dùng", parent=ad_trangchu)
        self.ad_menu_quanly_nguoidung.addAction(self.ad_menu_quanly_nguoidung_action)

        self.ad_menu_quanly_phim_action = QAction("Quản lý phim", parent=ad_trangchu)
        self.ad_menu_quanly_phim.addAction(self.ad_menu_quanly_phim_action)


        # Đặt kích thước cho từng cột
        self.tableWidget.setColumnWidth(0, 120)   # Cột "TOP"
        self.tableWidget.setColumnWidth(1, 600)  # Cột "TIÊU ĐỀ"
        self.tableWidget.setColumnWidth(2, 100)  # Cột "ĐIỂM"
        self.tableWidget.setColumnWidth(3, 150)  # Cột "ĐÁNH GIÁ"
        self.tableWidget.setColumnWidth(4, 220)  # Cột "CHI TIẾT"

        self.retranslateUi(ad_trangchu)
        QtCore.QMetaObject.connectSlotsByName(ad_trangchu)

    def retranslateUi(self, ad_trangchu):
        _translate = QtCore.QCoreApplication.translate
        ad_trangchu.setWindowTitle(_translate("ad_trangchu", "MainWindow"))
        self.ad_trangchu_them.setText(_translate("ad_trangchu", "THÊM"))
        self.ad_trangchu_sua.setText(_translate("ad_trangchu", "SỬA"))
        self.ad_trangchu_xoa.setText(_translate("ad_trangchu", "XÓA"))
        self.chublogphim.setText(_translate("ad_trangchu", "BLOG PHIM "))
        self.ad_trangchu_timkiem.setText(_translate("ad_trangchu", "TÌM KIẾM "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ad_trangchu", "Xếp hạng"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ad_trangchu", "Tên phim"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ad_trangchu", "Điểm"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ad_trangchu", "Số tập"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ad_trangchu", "Hành động"))
        self.chublogphim_2.setText(_translate("ad_trangchu", "TOP PHIM"))
        self.ad_menu_trangchu.setTitle(_translate("ad_trangchu", "TRANG CHỦ "))
        self.ad_menu_quanly_nguoidung.setTitle(_translate("ad_trangchu", "QUẢN LÝ NGƯỜI DÙNG "))
        self.ad_menu_quanly_phim.setTitle(_translate("ad_trangchu", "QUẢN LÝ PHIM "))

    def clear_table_selection(self, event):
        """Tắt chọn dòng khi click ra ngoài bảng"""
        self.tableWidget.clearSelection()
        QWidget.mousePressEvent(self.centralwidget, event)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ad_trangchu = QtWidgets.QMainWindow()
    ui = Ui_ad_trangchu()
    ui.setupUi(ad_trangchu)
    ad_trangchu.show()
    sys.exit(app.exec())
